
CREATE TABLE IF NOT EXISTS   `PersonasMes` (
  `PersonaId` int(11) NOT NULL DEFAULT '0',
  `Leg` int(11) NOT NULL,
  `ApellidoNombre` varchar(200) COLLATE utf8_spanish_ci DEFAULT NULL,
  `Cargo` varchar(45) COLLATE utf8_spanish_ci DEFAULT NULL,
  `D1` varchar(45) COLLATE utf8_spanish_ci DEFAULT NULL,
  `D2` varchar(45) COLLATE utf8_spanish_ci DEFAULT NULL,
  `D3` varchar(45) COLLATE utf8_spanish_ci DEFAULT NULL,
  `D4` varchar(45) COLLATE utf8_spanish_ci DEFAULT NULL,
  `D5` varchar(45) COLLATE utf8_spanish_ci DEFAULT NULL,
  `D6` varchar(45) COLLATE utf8_spanish_ci DEFAULT NULL,
  `D7` varchar(45) COLLATE utf8_spanish_ci DEFAULT NULL,
  `D8` varchar(45) COLLATE utf8_spanish_ci DEFAULT NULL,
  `D9` varchar(45) COLLATE utf8_spanish_ci DEFAULT NULL,
  `D10` varchar(45) COLLATE utf8_spanish_ci DEFAULT NULL,
  `D11` varchar(45) COLLATE utf8_spanish_ci DEFAULT NULL,
  `D12` varchar(45) COLLATE utf8_spanish_ci DEFAULT NULL,
  `D13` varchar(45) COLLATE utf8_spanish_ci DEFAULT NULL,
  `D14` varchar(45) COLLATE utf8_spanish_ci DEFAULT NULL,
  `D15` varchar(45) COLLATE utf8_spanish_ci DEFAULT NULL,
  `D16` varchar(45) COLLATE utf8_spanish_ci DEFAULT NULL,
  `D17` varchar(45) COLLATE utf8_spanish_ci DEFAULT NULL,
  `D18` varchar(45) COLLATE utf8_spanish_ci DEFAULT NULL,
  `D19` varchar(45) COLLATE utf8_spanish_ci DEFAULT NULL,
  `D20` varchar(45) COLLATE utf8_spanish_ci DEFAULT NULL,
  `D21` varchar(45) COLLATE utf8_spanish_ci DEFAULT NULL,
  `D22` varchar(45) COLLATE utf8_spanish_ci DEFAULT NULL,
  `D23` varchar(45) COLLATE utf8_spanish_ci DEFAULT NULL,
  `D24` varchar(45) COLLATE utf8_spanish_ci DEFAULT NULL,
  `D25` varchar(45) COLLATE utf8_spanish_ci DEFAULT NULL,
  `D26` varchar(45) COLLATE utf8_spanish_ci DEFAULT NULL,
  `D27` varchar(45) COLLATE utf8_spanish_ci DEFAULT NULL,
  `D28` varchar(45) COLLATE utf8_spanish_ci DEFAULT NULL,
  `D29` varchar(45) COLLATE utf8_spanish_ci DEFAULT NULL,
  `D30` varchar(45) COLLATE utf8_spanish_ci DEFAULT NULL,
  `D31` varchar(45) COLLATE utf8_spanish_ci DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci;
