
CREATE TABLE IF NOT EXISTS   `PersonasAnio` (
  `Id` int(11) NOT NULL AUTO_INCREMENT,
  `PersonaId` int(11) NOT NULL,
  `Mes` int(11) NOT NULL,
  `D1` varchar(5) COLLATE utf8_spanish_ci DEFAULT ' ',
  `D2` varchar(5) COLLATE utf8_spanish_ci DEFAULT ' ',
  `D3` varchar(5) COLLATE utf8_spanish_ci DEFAULT ' ',
  `D4` varchar(5) COLLATE utf8_spanish_ci DEFAULT ' ',
  `D5` varchar(5) COLLATE utf8_spanish_ci DEFAULT ' ',
  `D6` varchar(5) COLLATE utf8_spanish_ci DEFAULT ' ',
  `D7` varchar(5) COLLATE utf8_spanish_ci DEFAULT ' ',
  `D8` varchar(5) COLLATE utf8_spanish_ci DEFAULT ' ',
  `D9` varchar(5) COLLATE utf8_spanish_ci DEFAULT ' ',
  `D10` varchar(5) COLLATE utf8_spanish_ci DEFAULT ' ',
  `D11` varchar(5) COLLATE utf8_spanish_ci DEFAULT ' ',
  `D12` varchar(5) COLLATE utf8_spanish_ci DEFAULT ' ',
  `D13` varchar(5) COLLATE utf8_spanish_ci DEFAULT ' ',
  `D14` varchar(5) COLLATE utf8_spanish_ci DEFAULT ' ',
  `D15` varchar(5) COLLATE utf8_spanish_ci DEFAULT ' ',
  `D16` varchar(5) COLLATE utf8_spanish_ci DEFAULT ' ',
  `D17` varchar(5) COLLATE utf8_spanish_ci DEFAULT ' ',
  `D18` varchar(5) COLLATE utf8_spanish_ci DEFAULT ' ',
  `D19` varchar(5) COLLATE utf8_spanish_ci DEFAULT ' ',
  `D20` varchar(5) COLLATE utf8_spanish_ci DEFAULT ' ',
  `D21` varchar(5) COLLATE utf8_spanish_ci DEFAULT ' ',
  `D22` varchar(5) COLLATE utf8_spanish_ci DEFAULT ' ',
  `D23` varchar(5) COLLATE utf8_spanish_ci DEFAULT ' ',
  `D24` varchar(5) COLLATE utf8_spanish_ci DEFAULT ' ',
  `D25` varchar(5) COLLATE utf8_spanish_ci DEFAULT ' ',
  `D26` varchar(5) COLLATE utf8_spanish_ci DEFAULT ' ',
  `D27` varchar(5) COLLATE utf8_spanish_ci DEFAULT ' ',
  `D28` varchar(5) COLLATE utf8_spanish_ci DEFAULT ' ',
  `D29` varchar(5) COLLATE utf8_spanish_ci DEFAULT ' ',
  `D30` varchar(5) COLLATE utf8_spanish_ci DEFAULT ' ',
  `D31` varchar(5) COLLATE utf8_spanish_ci DEFAULT ' ',
  `E` int(11) DEFAULT NULL,
  `Fe` int(11) DEFAULT NULL,
  `V` int(11) DEFAULT NULL,
  `IC` int(11) DEFAULT NULL,
  `TE` int(11) DEFAULT NULL,
  `Tom` int(11) DEFAULT NULL,
  `TIC` int(11) DEFAULT NULL,
  `Ma` int(11) DEFAULT NULL,
  `TMa` int(11) DEFAULT NULL,
  `Ins` int(11) DEFAULT NULL,
  `TIns` int(11) DEFAULT NULL,
  `TFe` int(11) DEFAULT NULL,
  `Ac` int(11) DEFAULT NULL,
  `TAc` int(11) DEFAULT NULL,
  `LT` int(11) DEFAULT NULL,
  `TLT` int(11) DEFAULT NULL,
  `Na` int(11) DEFAULT NULL,
  `TNa` int(11) DEFAULT NULL,
  `Re` int(11) DEFAULT NULL,
  `TRe` int(11) DEFAULT NULL,
  `Ds` int(11) DEFAULT NULL,
  `TDs` int(11) DEFAULT NULL,
  `Cp` int(11) DEFAULT NULL,
  `TCp` int(11) DEFAULT NULL,
  PRIMARY KEY (`Id`,`PersonaId`,`Mes`)
) ENGINE=InnoDB AUTO_INCREMENT=1897 DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci;
