use tapelorena;

INSERT INTO Rubros (Nombre)
     VALUES
('ACTIVOS INTANGIBLES');
INSERT INTO Rubros (Nombre)
     VALUES
('AGRIC,GANADERIA,CAZA,SILVICULT');
INSERT INTO Rubros (Nombre)
     VALUES
('ALIMENTOS');
INSERT INTO Rubros (Nombre)
     VALUES
('ALQUILER');
INSERT INTO Rubros (Nombre)
     VALUES
('ALQUILER - BANCOS Y SEGUROS');
INSERT INTO Rubros (Nombre)
     VALUES
('ALQUILERES Y DERECHOS');
INSERT INTO Rubros (Nombre)
     VALUES
('ARTICULOS DEL HOGAR');
INSERT INTO Rubros (Nombre)
     VALUES
('ASISTENCIA SOCIAL AL PERSONAL');
INSERT INTO Rubros (Nombre)
     VALUES
('BANCOS Y SEGUROS');
INSERT INTO Rubros (Nombre)
     VALUES
('BAZAR Y MENAJE');
INSERT INTO Rubros (Nombre)
     VALUES
('BIENES PREEXISTENTES');
INSERT INTO Rubros (Nombre)
     VALUES
('CARPINTERIA');
INSERT INTO Rubros (Nombre)
     VALUES
('CEREMONIAL');
INSERT INTO Rubros (Nombre)
     VALUES
('CERRAJERIA');
INSERT INTO Rubros (Nombre)
     VALUES
('CINE/TELVIS./RADIO/FOTOGRAFIA');
INSERT INTO Rubros (Nombre)
     VALUES
('COMBUSTIBLES Y LUBRICANTES');
INSERT INTO Rubros (Nombre)
     VALUES
('COMPRA DE ACCIONES Y PARTICIPACIONES DE CAPITAL');
INSERT INTO Rubros (Nombre)
     VALUES
('CONSTRUCCION');
INSERT INTO Rubros (Nombre)
     VALUES
('CONSTRUCCIONES');
INSERT INTO Rubros (Nombre)
     VALUES
('CULTURA');
INSERT INTO Rubros (Nombre)
     VALUES
('DEPRECIACION Y AMORTIZACION');
INSERT INTO Rubros (Nombre)
     VALUES
('DESCUENTOS Y BONIFICACIONES');
INSERT INTO Rubros (Nombre)
     VALUES
('DISMINUCION DE CUENTAS Y DOCUMENTOS A PAGAR');
INSERT INTO Rubros (Nombre)
     VALUES
('DISMINUCION DE DEPOSITOS EN INSTITUCIONES PUBLICAS FINANCIERAS');
INSERT INTO Rubros (Nombre)
     VALUES
('DISMINUCION DE OTROS PASIVOS');
INSERT INTO Rubros (Nombre)
     VALUES
('DISMINUCION DE PRESTAMOS A CORTO PLAZO');
INSERT INTO Rubros (Nombre)
     VALUES
('DISMINUCION DE PRESTAMOS A LARGO PLAZO');
INSERT INTO Rubros (Nombre)
     VALUES
('DISMINUCION DEL PATRIMONIO');
INSERT INTO Rubros (Nombre)
     VALUES
('ELECTRICIDAD Y TELEFONIA');
INSERT INTO Rubros (Nombre)
     VALUES
('ELEMENTOS DE LIMPIEZA');
INSERT INTO Rubros (Nombre)
     VALUES
('ELEMENTOS DE ORTODONCIA');
INSERT INTO Rubros (Nombre)
     VALUES
('EQUIPO');
INSERT INTO Rubros (Nombre)
     VALUES
('EQUIPO DE OFICINA Y MUEBLES');
INSERT INTO Rubros (Nombre)
     VALUES
('EQUIPO EDUCACIONAL Y RECREAT.');
INSERT INTO Rubros (Nombre)
     VALUES
('EQUIPO MILITAR Y DE SEGURIDAD');
INSERT INTO Rubros (Nombre)
     VALUES
('EQUIPO MILITAR Y DE SEGURIDAD - ANAL. DE TELEFONOS Y LINEAS');
INSERT INTO Rubros (Nombre)
     VALUES
('EQUIPO SANITARIO Y DE LABORAT.');
INSERT INTO Rubros (Nombre)
     VALUES
('EQUIPOS');
INSERT INTO Rubros (Nombre)
     VALUES
('EQUIPOS DE OFICINA Y MUEBLES');
INSERT INTO Rubros (Nombre)
     VALUES
('EQUIPOS VARIOS');
INSERT INTO Rubros (Nombre)
     VALUES
('FERRETERIA');
INSERT INTO Rubros (Nombre)
     VALUES
('GASES INDUSTRIALES');
INSERT INTO Rubros (Nombre)
     VALUES
('GASTOS FIGURATIVOS DE LA ADMINISTRACION NACIONAL PARA');
INSERT INTO Rubros (Nombre)
     VALUES
('GASTOS FIGURATIVOS DE LA ADMINISTRACION NACIONAL PARA APLICACIONES');
INSERT INTO Rubros (Nombre)
     VALUES
('GASTOS FIGURATIVOS DE LA ADMINISTRACION NACIONAL PARA TRANSACCIONES DE');
INSERT INTO Rubros (Nombre)
     VALUES
('HERRAMIENTAS');
INSERT INTO Rubros (Nombre)
     VALUES
('HERRAMIENTAS Y REP. MAYORES');
INSERT INTO Rubros (Nombre)
     VALUES
('HERRERIA');
INSERT INTO Rubros (Nombre)
     VALUES
('IMPRENTA Y EDITORIALES');
INSERT INTO Rubros (Nombre)
     VALUES
('IMPUESTOS, DERECHOS, TASAS Y JUICIOS');
INSERT INTO Rubros (Nombre)
     VALUES
('INCREMENTO DE ACTIVOS DIFERIDOS Y ADELANTOS A PROVEEDORES Y CONTRATISTAS');
INSERT INTO Rubros (Nombre)
     VALUES
('INCREMENTO DE CUENTAS A COBRAR');
INSERT INTO Rubros (Nombre)
     VALUES
('INCREMENTO DE DISPONIBILIDADES');
INSERT INTO Rubros (Nombre)
     VALUES
('INCREMENTO DE DOCUMENTOS A COBRAR');
INSERT INTO Rubros (Nombre)
     VALUES
('INDUMENT TEXTIL Y CONFECCIONES');
INSERT INTO Rubros (Nombre)
     VALUES
('INFORMATICA');
INSERT INTO Rubros (Nombre)
     VALUES
('INMUEBLES');
INSERT INTO Rubros (Nombre)
     VALUES
('INSUMO P/ ARMAMENTO');
INSERT INTO Rubros (Nombre)
     VALUES
('INTERESES POR PRESTAMOS RECIBIDOS');
INSERT INTO Rubros (Nombre)
     VALUES
('JOYERIA Y ORFEBRERIA');
INSERT INTO Rubros (Nombre)
     VALUES
('LIBRERIA,PAP. Y UTILES OFICINA');
INSERT INTO Rubros (Nombre)
     VALUES
('MANTENIMIENTO, REPARACION Y LIMPIEZA');
INSERT INTO Rubros (Nombre)
     VALUES
('MAQUINARIA Y EQUIPO');
INSERT INTO Rubros (Nombre)
     VALUES
('MATERIALES DE CONSTRUCCION');
INSERT INTO Rubros (Nombre)
     VALUES
('METALES');
INSERT INTO Rubros (Nombre)
     VALUES
('METALURGIA');
INSERT INTO Rubros (Nombre)
     VALUES
('MINERALES');
INSERT INTO Rubros (Nombre)
     VALUES
('NAUTICA');
INSERT INTO Rubros (Nombre)
     VALUES
('No posee');
INSERT INTO Rubros (Nombre)
     VALUES
('OTRAS PERDIDAS');
INSERT INTO Rubros (Nombre)
     VALUES
('OTROS BIENES DE CONSUMO');
INSERT INTO Rubros (Nombre)
     VALUES
('OTROS SERVICIOS');
INSERT INTO Rubros (Nombre)
     VALUES
('PASAJES Y VIATICOS');
INSERT INTO Rubros (Nombre)
     VALUES
('PERSONAL CONTRATADO');
INSERT INTO Rubros (Nombre)
     VALUES
('PERSONAL PERMANENTE');
INSERT INTO Rubros (Nombre)
     VALUES
('PERSONAL TEMPORARIO');
INSERT INTO Rubros (Nombre)
     VALUES
('PINTURAS');
INSERT INTO Rubros (Nombre)
     VALUES
('PRESTAMOS A CORTO PLAZO');
INSERT INTO Rubros (Nombre)
     VALUES
('PRESTAMOS A LARGO PLAZO');
INSERT INTO Rubros (Nombre)
     VALUES
('PROD. MEDICO/FARMACEUTICO/LAB');
INSERT INTO Rubros (Nombre)
     VALUES
('PROD. MEDICO/FARMACEUTICOS/LAB');
INSERT INTO Rubros (Nombre)
     VALUES
('PROD. MEDICO/FARMACEUTICOS/LABPROD. MEDICO/FARMACEUTICOS/LAB');
INSERT INTO Rubros (Nombre)
     VALUES
('PROD. QUIMICOS,COMBUST.Y LUBR.');
INSERT INTO Rubros (Nombre)
     VALUES
('PROD.MEDICO/FARMACEUTICO/LAB');
INSERT INTO Rubros (Nombre)
     VALUES
('PRODUCTOS ALIMENTICIOS AGROPECUARIOS Y FORESTALES');
INSERT INTO Rubros (Nombre)
     VALUES
('PRODUCTOS DE CUERO Y CAUCHO');
INSERT INTO Rubros (Nombre)
     VALUES
('PRODUCTOS DE MINERALES NO METALICOS');
INSERT INTO Rubros (Nombre)
     VALUES
('PRODUCTOS DE PAPEL, CARTON E IMPRESOS');
INSERT INTO Rubros (Nombre)
     VALUES
('PRODUCTOS METALICOS');
INSERT INTO Rubros (Nombre)
     VALUES
('PRODUCTOS QUIMICOS, COMBUSTIBLES Y LUBRICANTES');
INSERT INTO Rubros (Nombre)
     VALUES
('PRODUCTOS VETERINARIOS');
INSERT INTO Rubros (Nombre)
     VALUES
('PROPROD. MEDICO/FARMACEUTICOS/LAB');
INSERT INTO Rubros (Nombre)
     VALUES
('QUIMICOS');
INSERT INTO Rubros (Nombre)
     VALUES
('REPUESTOS Y ACCESORIOS');
INSERT INTO Rubros (Nombre)
     VALUES
('SANITARIOS, PLOMERIA Y GAS');
INSERT INTO Rubros (Nombre)
     VALUES
('SER. PROFESIONAL Y COMERCIAL');
INSERT INTO Rubros (Nombre)
     VALUES
('SERV. CONSTRUC. EQ. HIDRAULICO');
INSERT INTO Rubros (Nombre)
     VALUES
('SERV. INSTALAC. EQ. BIOMETRICO');
INSERT INTO Rubros (Nombre)
     VALUES
('SERV. LASTRADO DE PROYECTILES');
INSERT INTO Rubros (Nombre)
     VALUES
('SERV. PRODUCCION DE TUBOS');
INSERT INTO Rubros (Nombre)
     VALUES
('SERV.PROFESIONAL Y COMERCIAL.');
INSERT INTO Rubros (Nombre)
     VALUES
('SERVICIO DE LA DEUDA EN MONEDA EXTRANJERA');
INSERT INTO Rubros (Nombre)
     VALUES
('SERVICIO DE LA DEUDA EN MONEDA NACIONAL');
INSERT INTO Rubros (Nombre)
     VALUES
('SERVICIO DE NOTICIAS');
INSERT INTO Rubros (Nombre)
     VALUES
('SERVICIOS');
INSERT INTO Rubros (Nombre)
     VALUES
('SERVICIOS BASICOS');
INSERT INTO Rubros (Nombre)
     VALUES
('SERVICIOS COMERCIALES Y FINANCIEROS');
INSERT INTO Rubros (Nombre)
     VALUES
('SERVICIOS EXTRAORDINARIOS');
INSERT INTO Rubros (Nombre)
     VALUES
('SERVICIOS TECNICOS Y PROFESIONALES');
INSERT INTO Rubros (Nombre)
     VALUES
('SERVISIOS BASICOS');
INSERT INTO Rubros (Nombre)
     VALUES
('SIN RUBRO');
INSERT INTO Rubros (Nombre)
     VALUES
('TAPICERIA');
INSERT INTO Rubros (Nombre)
     VALUES
('TEXTILES Y VESTUARIO');
INSERT INTO Rubros (Nombre)
     VALUES
('TITULOS Y VALORES');
INSERT INTO Rubros (Nombre)
     VALUES
('TRANSFERENCIAS A INSTITUCIONES PROVINCIALES Y MUNICIPALES PARA FINANCIAR');
INSERT INTO Rubros (Nombre)
     VALUES
('TRANSFERENCIAS A LA ADMINISTRACION NACIONAL');
INSERT INTO Rubros (Nombre)
     VALUES
('TRANSFERENCIAS A OTRAS ENTIDADES DEL SECTOR PUBLICO NACIONAL');
INSERT INTO Rubros (Nombre)
     VALUES
('TRANSFERENCIAS A UNIVERSIDADES NACIONALES');
INSERT INTO Rubros (Nombre)
     VALUES
('TRANSFERENCIAS AL EXTERIOR');
INSERT INTO Rubros (Nombre)
     VALUES
('TRANSFERENCIAS AL SECTOR PRIVADO PARA FINANCIAR GASTOS CORRIENTES');
INSERT INTO Rubros (Nombre)
     VALUES
('TRANSFERENCIAS AL SECTOR PRIVADO PARA FINANCIAR GASTOS DE CAPITAL');
INSERT INTO Rubros (Nombre)
     VALUES
('TRANSPORTE Y DEPOSITO');
INSERT INTO Rubros (Nombre)
     VALUES
('UTILES DE ESCRIT. OFIC -ENSEÑ.');
INSERT INTO Rubros (Nombre)
     VALUES
('UTILES Y PRODUCTOS DEPORTIVOS');
INSERT INTO Rubros (Nombre)
     VALUES
('VERIFICACION TECNICA VEHICULAR');
INSERT INTO Rubros (Nombre)
     VALUES
('VIDRIERIA');
INSERT INTO Rubros (Nombre)
     VALUES
('VIGILANCIA Y SEGURIDAD');
